'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Productos
    Public Property id As Integer
    Public Property nombre As String
    Public Property stock As Integer
    Public Property precio As Decimal
    Public Property idCategoria As Integer

    Public Overridable Property Categorias As Categorias

End Class
